{% set name = "stingray" %}
{% set version = "2.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b417a3ee42778d7351f3932fa130486614882a41b54b5f02a4603cc2b76e404e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - astropy-base >=4.0
    - matplotlib-base >=3.0,!=3.4.0
    - numpy >=1.17.0
    - scipy >=1.1.0

test:
  imports:
    - scipy
    - numpy
    - astropy
    - stingray
    - stingray.modeling
    - stingray.modeling.tests
    - stingray.pulse
    - stingray.pulse.tests
    - stingray.simulator
    - stingray.simulator.tests
    - stingray.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/StingraySoftware/stingray
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: The Next Generation Spectral Timing Software

  description: |
    This Astropy-affiliated software package merges existing efforts for a timing package in Python
    and provides the basis for developing spectral-timing analysis tools. It is
    structured with the best guidelines for modern open-source programming,
    following the example of Astropy.
  doc_url: http://stingray.readthedocs.io/
  dev_url: https://github.com/StingraySoftware/stingray

extra:
  recipe-maintainers:
    - matteobachetti
    - dhuppenkothen
    - evandromr
