{% set name = "stingray" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6544d5e43986878946fccae22a686db3aa925ebe244b1819c4d75e14bf14dfd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - astropy
    - matplotlib-base >=1.3
    - numpy >=1.16.0
    - scipy >=0.18.0

test:
  imports:
    - scipy
    - numpy
    - astropy
    - stingray
    - stingray.modeling
    - stingray.modeling.tests
    - stingray.pulse
    - stingray.pulse.tests
    - stingray.simulator
    - stingray.simulator.tests
    - stingray.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/StingraySoftware/stingray
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: The Next Generation Spectral Timing Software

  description: |
    This Astropy-affiliated software package merges existing efforts for a timing package in Python
    and provides the basis for developing spectral-timing analysis tools. It is
    structured with the best guidelines for modern open-source programming,
    following the example of Astropy.
  doc_url: http://stingray.readthedocs.io/
  dev_url: https://github.com/StingraySoftware/stingray

extra:
  recipe-maintainers:
    - matteobachetti
    - dhuppenkothen
    - evandromr
