{% set name = "stingray" %}
{% set version = "0.3" %}
{% set sha256 = "b6544d5e43986878946fccae22a686db3aa925ebe244b1819c4d75e14bf14dfd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [py<35]
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - numpy >=1.16.0
  run:
    - python
    - astropy
    - scipy >=0.18.0
    - numpy >=1.16.0
    # - numpy 1.17.*  # [py==38]
    - numpy         # [py>=39 or build_platform != target_platform or  python_impl == 'pypy']
    - matplotlib-base >=1.3

test:
  imports:
    - scipy
    - numpy
    - astropy
    - stingray
    - stingray.modeling
    - stingray.modeling.tests
    - stingray.pulse
    - stingray.pulse.tests
    - stingray.simulator
    - stingray.simulator.tests
    - stingray.tests

about:
  home: http://github.com/StingraySoftware/stingray
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: The Next Generation Spectral Timing Software

  description: |
    This Astropy-affiliated software package merges existing efforts for a timing package in Python
    and provides the basis for developing spectral-timing analysis tools. It is
    structured with the best guidelines for modern open-source programming,
    following the example of Astropy.
  doc_url: http://stingray.readthedocs.io/
  dev_url: https://github.com/StingraySoftware/stingray

extra:
  recipe-maintainers:
    - matteobachetti
    - dhuppenkothen
    - evandromr
