appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AfHeTrMnwS8dCB3TkJB18xbN+henZyKHw/WcKtZhIkSWf2uDC1w6MsFNY+7DUqIKZWWwCWKYxb5ePOuw2mAmdRLJn8U4vz4qoEgwVhoUvFgdKyDm6qRvyUOfCI3QmSXyqXiP9t7t2hz31UDd3E/maHV6hLo1ERQ6OTXBwrBRrwFFBSMrxgd2GRatkQ44wBcmxAuNcP0lv4STMHbHP95tatno24d8xh4JwvYucN647FfYWJNHKXigEbtxJnDJV0g8x9Vpvo/Bs1D4SrEBFNSF9F2IU0t8rmLRxkOVt1b3IsW7KoJR1k2rlrzccO37NhcuK2Qpi0lE6o9gUA5ZS3Nv6Yy36IZjAgO5svvDNLdKU9cGrJEERGhYdEalA5HpVDKGno6bCskrGsuVRcp60ip/xTbulMn7xNKi8DDwk+YMgCPG7zSmIDqgkCE66PwHObw46YObNLXlzuLlPS0rp7ojNkplF101uhjQumu2EJjhPFqZX+FPVNNOUOmNcBWLqbfTF4xVpxc1LwZlmSAFN+1DFrIiJsKKW9+gKjUMkTgDnYlJ+y7Jx/pAckIIO2DGxj7EwNM8iNzAytT71gD5t6cz0cGi1V2zxRH7kmjTdLa/pSzS2SeotPbnfr5WM2HYtm+SQZm2wJTzkiDa8z817bj4Y3QGnlMvqqpI6c/6uMW2wvw=}
provider:
  win: azure
conda_forge_output_validation: true
