travis:
  secure:
    BINSTAR_TOKEN: qTGQLBblHSuBhsW/HnsQyVFITj9k/b8DhG3xYHz/uF66S/CzObTZDou6aFQO6UETj2ZuMKe5ukN5pB8a9HKzkPUgGijTkhTbtOh9P73rmVPlmJD5DB5TYifkpN3H2IFIzO5U/ZF4m01Ghl9l6lw4De/vRKypJlXH2Y2SD5wWSneikS/SqqtT2xq7jnTSSjNRFuHlC7g+SftaTpE9CdaBMAh5JXxTcBdyvx6Oe2f1xHG/3XkqTtSnbzx8fRy9gofKrw2beSvAUKywrvH+QE+ZJ7uGcUutNeHpD/vWHmhLen3Sdfzq9bLsrZs6Eh7uBDun+b2fdzLeK2HsS8dJ6h1p8vIxlAfVR+N/xYNzoE58OF8yiOeFHy9txeKR/0STxtaNHV2o8Q69EEn3faU0x8ja0JcnR6lxyLkgZp7OiCIw2B3bTQ0x5J6zKrJYYvCikE7le6AXNT/cAX387sXiKI27pp/ilTyc4N1Oe5cgPJbZPrXL7WVoFDhmmIK4CTUJmPeOF7CB4mEX91U2iRYeKSyPC9c7wUHaySNP7fNTfqWlkaRyi2vLqVIsS0pk4f1jneGSCQXLdrd1LwUsY3MX/7Aq3QRSOT5+s1+IqbCjOzb2/F4pBvVw0RWM1jhXS6YQAoRovi+mkaCAykUgTumukkjT9OAnxML3mAGyrAxYpzCnnqs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
